config/routes.rb
Rails.application.routes.draw do
  get 'images/upload'
  post 'images/upload' => 'images#perform_upload'
  get 'images/download' => 'images#download'
  root 'images#upload'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/montage.rb
class Montage < ApplicationRecord
  include MiniMagick

  before_validation :create_combined_image

  mount_uploader :combined_image, ImageUploader

  validates :left_image, presence: true
  validates :right_image, presence: true, uniqueness: { scope: :left_image }
  validates :combined_image, presence: true

  private

  def create_combined_image
    if left_image.nil? || right_image.nil?
      return
    end

    image1 = Image.open left_image
    image2 = Image.open right_image
    tempfile = Tempfile.new('convert')

    Tool::Convert.new do |convert|
      convert << image1.path
      convert << image2.path
      convert.resize "x#{image1.height}"
      convert.border 20
      convert << '+append'
      convert.border 20
      convert << '+repage'
      convert << tempfile.path
    end

    montage = Image.open(tempfile.path)
    logo = Image.open('app/assets/images/generic_logo.png').resize "x#{montage.height / 15}^"

    result = montage.composite(logo) do |c|
      c.compose :Over
      c.geometry '+100+100'
      c.gravity 'SouthEast'
    end

    self.combined_image = result
    tempfile.delete
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include MontagesHelper

  def upload
  end

  def perform_upload
    begin
      if image_params.content_type != 'text/csv'
        flash[:error] = 'Uploaded file not csv'
      else
        import_csv(image_params.tempfile)
        flash[:info] = 'Upload submitted'
      end
    rescue ActionController::ParameterMissing => er
      flash[:error] = 'No file uploaded'
    end

    redirect_to root_path
  end

  def download
    if Montage.count == 0
      flash[:info] = 'No images uploaded.'
      redirect_to root_path
    else
      csv = export_csv
      send_data csv, filename: 'montages.csv'
    end
  end

  private

  def image_params
    params.require(:images).require(:csv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/montages_helper.rb
require 'csv'
require 'open-uri'

module MontagesHelper
  def import_csv(csv)
    CSV.foreach(csv.path) do |row|
      create_montage(row)
    end
  end


  def export_csv
    CSV.generate do |csv|
      Montage.all.each { |m| csv << [m.left_image, m.right_image, root_url.chomp('/') + m.combined_image.url] }
    end
  end

  private

  def create_montage(row)
    MontageWorker.perform_async(row)
  end
end

app/views/images/upload.html.erb
<div class="container">
  <h1>Image Spreadsheet Uploader</h1>
  <%= simple_form_for :images, method: :post, url: images_upload_path, html: { class: 'image-upload-form' } do |f| %>
      <%= f.input :csv, as: :file, input_html: { class: 'filestyle', :'data-buttonBefore' => 'true' } %>
      <%= f.button :submit, 'Upload' %>
  <% end %>

  <%= button_to 'Download Processed', images_download_path, method: :get, class: 'btn btn-primary', id: 'image-download-button'  %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>', '<%= type %>');
      <% end %>
    </script>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SilkFred Assignment" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SilkFred Assignment" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>